### ISSUE TITLE
Panel PCB has errors.

### ISSUE THREAD

**Issue by tomsteed** [Testbild-synth/HAGIWO_arduino_oscillator#1]
Hi, 
The panel pcb has errors with the jack sockets. 3 stacked each side should mean 9 solder points, 3 per socket. There are only 8 so the sockets wont fit.
![image](https://user-images.githubusercontent.com/126072841/220615786-77f52b73-5273-465c-8e27-76c78369ee4c.png)

**Comment by Testbild-synth** [comment]
This is deliberate to minimize size. The holes are wider so you can fit two
opposing ground leads into the same hole. Its slightly uncommon but I've
seen other builds do this too and imo it's not too much of a hassle when
building.

tomsteed ***@***.***> schrieb am Mi., 22. Feb. 2023, 21:09:

**Comment by tomsteed** [comment]
Thank you. Just did a dry fit and it will work.
